[project]
name = "codigofacilito-dataviz-efectiva"
version = "0.1.0"
description = "Código para la clase del curso de DataViz Efectiva de CódigoFacilito"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.4.1",
    "ipykernel>=6.29.5",
    "vega-datasets>=0.9.0",
]
